### ISSUE TITLE
schema文件怎么定义，请指教

### ISSUE THREAD

**Issue by guohuihot** [yisbug/egg-mongoose-framework#1]
请问应用里的schema文件夹里的文件怎么定义，能给个例子吗？
另外报错，你是怎么解决的
```
[ERR_ASSERTION]: Symbol.for('egg#eggPath') is required on Application
--
```

**Comment by yisbug** [comment]
正常定义就是了，格式参考 mongoose 的 schema 定义，例如：app/schema/test.js
```
module.exports={
    name:{
        type:String
    }
}
```
之后，即可使用 ctx.service.test

**Comment by yisbug** [comment]
可以参考这个项目的结构：https://github.com/yisbug/egg-mongoose-curd

**Comment by yisbug** [comment]
已添加测试用例，可直接参考使用。
